/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.0.1_@babel+parser@7.26.7_embla-carousel@8.6.0_rollup@2.79.2_superstruct@2.0.2_type_myng3qdu6mi7jmehzczpzz4t3m/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@4.0.1_@babel+parser@7.26.7_embla-carousel@8.6.0_rollup@2.79.2_superstruct@2.0.2_type_myng3qdu6mi7jmehzczpzz4t3m/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.0.1_@babel+parser@7.26.7_embla-carousel@8.6.0_rollup@2.79.2_superstruct@2.0.2_type_myng3qdu6mi7jmehzczpzz4t3m/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.0.1_@babel+parser@7.26.7_embla-carousel@8.6.0_rollup@2.79.2_superstruct@2.0.2_type_myng3qdu6mi7jmehzczpzz4t3m/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UFieldGroup: typeof import('./node_modules/.pnpm/@nuxt+ui@4.0.1_@babel+parser@7.26.7_embla-carousel@8.6.0_rollup@2.79.2_superstruct@2.0.2_type_myng3qdu6mi7jmehzczpzz4t3m/node_modules/@nuxt/ui/dist/runtime/components/FieldGroup.vue')['default']
    UForm: typeof import('./node_modules/.pnpm/@nuxt+ui@4.0.1_@babel+parser@7.26.7_embla-carousel@8.6.0_rollup@2.79.2_superstruct@2.0.2_type_myng3qdu6mi7jmehzczpzz4t3m/node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@4.0.1_@babel+parser@7.26.7_embla-carousel@8.6.0_rollup@2.79.2_superstruct@2.0.2_type_myng3qdu6mi7jmehzczpzz4t3m/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.0.1_@babel+parser@7.26.7_embla-carousel@8.6.0_rollup@2.79.2_superstruct@2.0.2_type_myng3qdu6mi7jmehzczpzz4t3m/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.0.1_@babel+parser@7.26.7_embla-carousel@8.6.0_rollup@2.79.2_superstruct@2.0.2_type_myng3qdu6mi7jmehzczpzz4t3m/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./node_modules/.pnpm/@nuxt+ui@4.0.1_@babel+parser@7.26.7_embla-carousel@8.6.0_rollup@2.79.2_superstruct@2.0.2_type_myng3qdu6mi7jmehzczpzz4t3m/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    URadioGroup: typeof import('./node_modules/.pnpm/@nuxt+ui@4.0.1_@babel+parser@7.26.7_embla-carousel@8.6.0_rollup@2.79.2_superstruct@2.0.2_type_myng3qdu6mi7jmehzczpzz4t3m/node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.vue')['default']
    USelect: typeof import('./node_modules/.pnpm/@nuxt+ui@4.0.1_@babel+parser@7.26.7_embla-carousel@8.6.0_rollup@2.79.2_superstruct@2.0.2_type_myng3qdu6mi7jmehzczpzz4t3m/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USeparator: typeof import('./node_modules/.pnpm/@nuxt+ui@4.0.1_@babel+parser@7.26.7_embla-carousel@8.6.0_rollup@2.79.2_superstruct@2.0.2_type_myng3qdu6mi7jmehzczpzz4t3m/node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
    UTabs: typeof import('./node_modules/.pnpm/@nuxt+ui@4.0.1_@babel+parser@7.26.7_embla-carousel@8.6.0_rollup@2.79.2_superstruct@2.0.2_type_myng3qdu6mi7jmehzczpzz4t3m/node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
  }
}
